name: Tests and Build

on:
  workflow_call:

  build:
    name: 🐋 Save docker image
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout to current branch
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: backend
          push:  github.ref_type == 'tag' && github.ref == 'refs/heads/main'
          tags: ${{ env.REGISTRY }}/${{ github.actor }}/fastapi:${{ github. }}